### ISSUE TITLE
Could not find a suitable constructor in com.netflix.titus.gateway.endpoint.v3.SupplementaryServiceLocationConfiguration

### ISSUE THREAD

**Issue by sjabasti** [Netflix/titus-control-plane#384]
When running the current master branch, this error occurs in the gateway service:

```
Could not find a suitable constructor in com.netflix.titus.gateway.endpoint.v3.SupplementaryServiceLocationConfiguration. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
gateway_1       |   at com.netflix.titus.gateway.endpoint.v3.SupplementaryServiceLocationConfiguration.class(SupplementaryServiceLocationConfiguration.java:17)
gateway_1       |   while locating com.netflix.titus.gateway.endpoint.v3.SupplementaryServiceLocationConfiguration
gateway_1       |     for the 1st parameter of com.netflix.titus.gateway.endpoint.v3.ConfigurableReactorHttpClientFactory.<init>(ConfigurableReactorHttpClientFactory.java:18)
gateway_1       |   at com.netflix.titus.gateway.endpoint.GatewayEndpointModule.configure(GatewayEndpointModule.java:26) (via modules: com.google.inject.util.Modules$CombinedModule -> com.netflix.titus.gateway.startup.TitusGatewayModule -> com.netflix.titus.gateway.endpoint.GatewayEndpointModule)
gateway_1       | 
gateway_1       | 1 error
gateway_1       | 	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
gateway_1       | 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
gateway_1       | 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
gateway_1       | 	at com.google.inject.Guice.createInjector(Guice.java:99)
gateway_1       | 	at com.google.inject.Guice.createInjector(Guice.java:84)
gateway_1       | 	at com.netflix.governator.LifecycleInjectorCreator.createInjector(LifecycleInjectorCreator.java:100)
gateway_1       | 	at com.netflix.governator.LifecycleInjectorCreator.createInjector(LifecycleInjectorCreator.java:38)
gateway_1       | 	at com.netflix.governator.InjectorBuilder.createInjector(InjectorBuilder.java:209)
gateway_1       | 	at com.netflix.governator.InjectorBuilder.createInjector(InjectorBuilder.java:230)
gateway_1       | 	at com.netflix.titus.gateway.startup.TitusGateway.main(TitusGateway.java:60)
```

It is probably due to the inject of SupplementaryServiceLocationConfiguration in class ConfigurableReactorHttpClientFactory while SupplementaryServiceLocationConfiguration has a constructor with a Config parameter but without an inject

ConfigurableReactorHttpClientFactory >
https://github.com/Netflix/titus-control-plane/blob/670719bcd785758ce696ea1e877ee57d7b9d1242/titus-server-gateway/src/main/java/com/netflix/titus/gateway/endpoint/v3/ConfigurableReactorHttpClientFactory.java#L18

SupplementaryServiceLocationConfiguration.java >
https://github.com/Netflix/titus-control-plane/blob/0c74f92e953d6e2422f69e7f8a8d072deb4cd0c0/titus-server-gateway/src/main/java/com/netflix/titus/gateway/endpoint/v3/SupplementaryServiceLocationConfiguration.java#L17

**Comment by sjabasti** [comment]
@dan-at-teza Something like that is missing, but I am trying to run the latest master commit (https://github.com/Netflix/titus-control-plane/commit/25e125559b4165cc02e4a4e8772c79df3a13186f). I am trying to use the docker-compose way as described in the Readme. No files have been changed in my local environment. After running docker-compose up -d the gateway exits immediately with previously mentioned error message. So I am wondering if it is a local problem?
